# Generated by Django 5.0.14 on 2025-11-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='ecommerce_p_slug_b8decd_idx',
            old_name='ecommerce_p_slug_4cc199_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='ecommerce_p_is_feat_277015_idx',
            old_name='ecommerce_p_is_feat_ffa22d_idx',
        ),
    ]
